# Header
menu:
  Home: /
  # Tags: /tags
  Archives: /archives
  # Categories: /categories
rss: /atom.xml

# Content
excerpt_link: 阅读更多
# fancybox: true


title: 二刺螈小破站


# Sidebar
sidebar: right
widgets:
- category
- tag
# - tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
- tagcloud
- archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
# google_analytics:
# gauges_analytics:
favicon: /images/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:


